services:
  management-information:
    build:
      target: dev
    ports:
      - '3456:3456'
    volumes:
      - ./management-information/.air.toml:/app/management-information/.air.toml
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
      - ./management-information/internal:/app/management-information/internal
      - ./management-information/main_test.go:/app/management-information/main_test.go
      - ./management-information/main.go:/app/management-information/main.go
      - ./management-information/web/static:/app/management-information/web/static
      - ./management-information/web/template:/app/management-information/web/template

  yarn:
    command: watch

  json-server:
    build:
      dockerfile: docker/json-server/Dockerfile
    volumes:
      - ./json-server/config:/app/config
    ports:
      - '3000:3000'