# Hot-reloading with Air - https://github.com/cosmtrek/air

root = "."
tmp_dir = "tmp"

[build]
exclude_dir = ["tmp"]
cmd = "go build -gcflags='all=-N -l' -o /tmp/main"
full_bin = "dlv exec --accept-multiclient --log --headless --continue --listen :3456 --api-version 2 /tmp/main"
include_ext = ["go"]